<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240827042334 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE country_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE country (id INT NOT NULL, name VARCHAR(255) NOT NULL, nombre VARCHAR(255) NOT NULL, iso2 VARCHAR(2) NOT NULL, currency_name VARCHAR(50) NOT NULL, currency_sign VARCHAR(5) NOT NULL, PRIMARY KEY(id))');
        $this->addSql("INSERT INTO country (id,nombre,name,iso2,currency_name,currency_sign) values 
            (1,'Afganistán','Afghanistan','AF','Afghani','AFN'),
            (2,'Albania','Albania','AL','Lek','ALL'),
            (3,'Argelia','Algeria','DZ','Dinar argelino','DZD'),
            (4,'Angola','Angola','AO','Kwanza','AOA'),
            (5,'Antigua y Barbuda','Antigua and Barbuda','AG','Dólar del Caribe Oriental','XCD'),
            (6,'Argentina','Argentina','AR','Peso argentino','ARS'),
            (7,'Armenia','Armenia','AM','Dram','AMD'),
            (8,'Aruba, Curazao y Sint Maarten','Aruba, Curaçao and Sint Maarten','AW','Florín arubeño','AWG'),
            (9,'Australia','Australia','AU','Dólar australiano','AUD'),
            (10,'Austria','Austria','AT','Euro','EUR'),
            (11,'Azerbaiyán','Azerbaijan','AZ','Manat','AZN'),
            (12,'Bahamas','Bahamas','BS','Dólar bahameño','BSD'),
            (13,'Bahréin','Bahrain','BH','Dinar bareiní','BHD'),
            (14,'Bangladés','Bangladesh','BD','Taka','BDT'),
            (15,'Barbados','Barbados','BB','Dólar de Barbados','BBD'),
            (16,'Bielorrusia','Belarus','BY','Rublo bielorruso','BYN'),
            (17,'Bélgica','Belgium','BE','Euro','EUR'),
            (18,'Belice','Belize','BZ','Dólar de Belice','BZD'),
            (19,'Benín','Benin','BJ','Franco CFA','XOF'),
            (20,'Bhután','Bhutan','BT','Ngultrum','BTN'),
            (21,'Bolivia','Bolivia','BO','Boliviano','BOB'),
            (22,'Bosnia y Herzegovina','Bosnia and Herzegovina','BA','Marco','BAM'),
            (23,'Botsuana','Botswana','BW','Pula','BWP'),
            (24,'Brasil','Brazil','BR','Real','BRL'),
            (25,'Brunéi Darussalam','Brunei Darussalam','BN','Dólar de Brunéi','BND'),
            (26,'Bulgaria','Bulgaria','BG','Lev','BGN'),
            (27,'Burkina Faso','Burkina Faso','BF','Franco CFA','XOF'),
            (28,'Burundi','Burundi','BI','Franco burundés','BIF'),
            (29,'Camboya','Cambodia','KH','Riel','KHR'),
            (30,'Camerún','Cameroon','CM','Franco CFA','XAF'),
            (31,'Canadá','Canada','CA','Dólar canadiense','CAD'),
            (32,'Cabo Verde','Cape Verde','CV','Escudo caboverdiano','CVE'),
            (33,'República Centroafricana','Central African Rep.','CF','Franco CFA','XAF'),
            (34,'Chad','Chad','TD','Franco CFA','XAF'),
            (35,'Chile','Chile','CL','Peso chileno','CLP'),
            (36,'China','China','CN','Yuan','CNY'),
            (37,'Colombia','Colombia','CO','Peso colombiano','COP'),
            (38,'Comoras','Comoros','KM','Franco comorano','KMF'),
            (39,'Congo','Congo','CG','Franco CFA','XAF'),
            (40,'Costa Rica','Costa Rica','CR','Colón','CRC'),
            (41,'Costa de Marfil','Côte d Ivoire','CI','Franco CFA','XOF'),
            (42,'Croacia','Croatia','HR','Kuna','HRK'),
            (43,'Cuba','Cuba','CU','Peso cubano','CUP'),
            (44,'Chipre','Cyprus','CY','Euro','EUR'),
            (45,'Chequia','Czechia','CZ','Corona checa','CZK'),
            (46,'República Popular Democrática de Corea','Dem People s Rep. of Korea','KP','Won','KPW'),
            (47,'República Democrática del Congo','Democratic Republic of the Congo','CD','Franco congoleño','CDF'),
            (48,'Dinamarca','Denmark','DK','Corona danesa','DKK'),
            (49,'Yibuti','Djibouti','DJ','Franco de Yibuti','DJF'),
            (50,'Dominica','Dominica','DM','Dólar del Caribe Oriental','XCD'),
            (51,'República Dominicana','Dominican Republic','DO','Peso dominicano','DOP'),
            (52,'Ecuador','Ecuador','EC','Dólar estadounidense','USD'),
            (53,'Egipto','Egypt','EG','Libra egipcia','EGP'),
            (54,'El Salvador','El Salvador','SV','Dólar estadounidense','USD'),
            (55,'Guinea Ecuatorial','Equatorial Guinea','GQ','Franco CFA','XAF'),
            (56,'Eritrea','Eritrea','ER','Nakfa','ERN'),
            (57,'Estonia','Estonia','EE','Euro','EUR'),
            (58,'Esuatini','Eswatini','SZ','Lilangeni','SZL'),
            (59,'Etiopía','Ethiopia','ET','Birr','ETB'),
            (60,'Fiyi','Fiji','FJ','Dólar de Fiyi','FJD'),
            (61,'Finlandia','Finland (including the Åland Islands)','FI','Euro','EUR'),
            (62,'Francia','France','FR','Euro','EUR'),
            (63,'Gabón','Gabon','GA','Franco CFA','XAF'),
            (64,'Gambia','Gambia','GM','Dalasi','GMD'),
            (65,'Georgia','Georgia','GE','Lari','GEL'),
            (66,'Alemania','Germany','DE','Euro','EUR'),
            (67,'Ghana','Ghana','GH','Cedi','GHS'),
            (68,'Grecia','Greece','GR','Euro','EUR'),
            (69,'Granada','Grenada','GD','Dólar del Caribe Oriental','XCD'),
            (70,'Guatemala','Guatemala','GT','Quetzal','GTQ'),
            (71,'Guinea','Guinea','GN','Franco CFA','XOF'),
            (72,'Guinea-Bisáu','Guinea-Bissau','GW','Franco CFA','XOF'),
            (73,'Guyana','Guyana','GY','Dólar guyanés','GYD'),
            (74,'Haití','Haiti','HT','Gourde','HTG'),
            (75,'Honduras','Honduras','HN','Lempira','HNL'),
            (76,'Hungría','Hungary','HU','Forint','HUF'),
            (77,'Islandia','Iceland','IS','Corona islandesa','ISK'),
            (78,'India','India','IN','Rupia india','INR'),
            (79,'Indonesia','Indonesia','ID','Rupia indonesia','IDR'),
            (80,'Irán','Iran (Islamic Rep.)','IR','Rial iraní','IRR'),
            (81,'Irak','Iraq','IQ','Dinar iraquí','IQD'),
            (82,'Irlanda','Ireland','IE','Euro','EUR'),
            (83,'Israel','Israel','IL','Nuevo shéquel','ILS'),
            (84,'Italia','Italy','IT','Euro','EUR'),
            (85,'Jamaica','Jamaica','JM','Dólar jamaiquino','JMD'),
            (86,'Japón','Japan','JP','Yen','JPY'),
            (87,'Jordania','Jordan','JO','Dinar jordano','JOD'),
            (88,'Kazajistán','Kazakhstan','KZ','Tenge','KZT'),
            (89,'Kenia','Kenya','KE','Chelín keniano','KES'),
            (90,'Kiribati','Kiribati','KI','Dólar australiano','AUD'),
            (91,'Corea','Korea','KR','Won','KRW'),
            (92,'Kuwait','Kuwait','KW','Dinar kuwaití','KWD'),
            (93,'Kirguistán','Kyrgyzstan','KG','Som','KGS'),
            (94,'República Democrática Popular Lao','Lao People s Dem. Rep.','LA','Kip','LAK'),
            (95,'Letonia','Latvia','LV','Euro','EUR'),
            (96,'Líbano','Lebanon','LB','Libra libanesa','LBP'),
            (97,'Lesoto','Lesotho','LS','Loti','LSL'),
            (98,'Liberia','Liberia','LR','Dólar liberiano','LRD'),
            (99,'Liechtenstein','Liechtenstein','LI','Franco suizo','CHF'),
            (100,'Lituania','Lithuania','LT','Euro','EUR'),
            (101,'Luxemburgo','Luxembourg','LU','Euro','EUR'),
            (102,'Madagascar','Madagascar','MG','Ariary','MGA'),
            (103,'Malaui','Malawi','MW','Kwacha','MWK'),
            (104,'Malasia','Malaysia','MY','Ringgit','MYR'),
            (105,'Maldivas','Maldives','MV','Rupia','MVR'),
            (106,'Malí','Mali','ML','Franco CFA','XOF'),
            (107,'Malta','Malta','MT','Euro','EUR'),
            (108,'Mauritania','Mauritania','MR','Ouguiya','MRU'),
            (109,'Mauricio','Mauritius','MU','Rupia','MUR'),
            (110,'México','Mexico','MX','Peso','MXN'),
            (111,'Moldavia','Moldova','MD','Leu','MDL'),
            (112,'Mónaco','Monaco','MC','Euro','EUR'),
            (113,'Mongolia','Mongolia','MN','Tugrik','MNT'),
            (114,'Montenegro','Montenegro','ME','Euro','EUR'),
            (115,'Marruecos','Morocco','MA','Dirham','MAD'),
            (116,'Mozambique','Mozambique','MZ','Metical','MZN'),
            (117,'Myanmar','Myanmar','MM','Kyat','MMK'),
            (118,'Namibia','Namibia','NA','Dólar','NAD'),
            (119,'Nauru','Nauru','NR','Dólar australiano','AUD'),
            (120,'Nepal','Nepal','NP','Rupia','NPR'),
            (121,'Países Bajos','Netherlands','NL','Euro','EUR'),
            (122,'Nueva Zelanda','New Zealand','NZ','Dólar neozelandés','NZD'),
            (123,'Nicaragua','Nicaragua','NI','Córdoba','NIO'),
            (124,'Níger','Niger','NE','Franco CFA','XOF'),
            (125,'Nigeria','Nigeria','NG','Naira','NGN'),
            (126,'Macedonia del Norte','North Macedonia','MK','Denar','MKD'),
            (127,'Noruega','Norway','NO','Corona','NOK'),
            (128,'Omán','Oman','OM','Rial','OMR'),
            (129,'Territorios de Ultramar','Overseas Territories','	-','Libra esterlina','GBP'),
            (130,'Pakistán','Pakistan','PK','Rupia','PKR'),
            (131,'Panamá','Panama','PA','Balboa','PAB'),
            (132,'Papúa Nueva Guinea','Papua New Guinea','PG','Kina','PGK'),
            (133,'Paraguay','Paraguay','PY','Guaraní','PYG'),
            (134,'Perú','Peru','PE','Sol','PEN'),
            (135,'Filipinas','Philippines','PH','Peso','PHP'),
            (136,'Polonia','Poland','PL','Zloty','PLN'),
            (137,'Portugal','Portugal','PT','Euro','EUR'),
            (138,'Catar','Qatar','QA','Riyal','QAR'),
            (139,'Rumania','Romania','RO','Leu','RON'),
            (140,'Federación Rusa','Russian Federation','RU','Rublo','RUB'),
            (141,'Ruanda','Rwanda','RW','Franco ruandés','RWF'),
            (142,'San Cristóbal y Nieves','Saint Christopher and Nevis','KN','Dólar del Caribe Oriental','XCD'),
            (143,'Santa Lucía','Saint Lucia','LC','Dólar del Caribe Oriental','XCD'),
            (144,'San Vicente y las Granadinas','Saint Vincent and the Grenadines','VC','Dólar del Caribe Oriental','XCD'),
            (145,'Samoa','Samoa','WS','Tala','WST'),
            (146,'San Marino','San Marino','SM','Euro','EUR'),
            (147,'Santo Tomé y Príncipe','Sao Tome and Principe','ST','Dobra','STN'),
            (148,'Arabia Saudita','Saudi Arabia','SA','Riyal','SAR'),
            (149,'Senegal','Senegal','SN','Franco CFA','XOF'),
            (150,'Serbia','Serbia','RS','Dinar','RSD'),
            (151,'Seychelles','Seychelles','SC','Rupia','SCR'),
            (152,'Sierra Leona','Sierra Leone','SL','Leone','SLL'),
            (153,'Singapur','Singapore','SG','Dólar singapurense','SGD'),
            (154,'Eslovaquia','Slovakia','SK','Euro','EUR'),
            (155,'Eslovenia','Slovenia','SI','Euro','EUR'),
            (156,'Islas Salomón','Solomon Islands','SB','Dólar de las Islas Salomón','SBD'),
            (157,'Somalia','Somalia','SO','Chelín somalí','SOS'),
            (158,'Sudáfrica','South Africa','ZA','Rand','ZAR'),
            (159,'Sudán del Sur','South Sudan','SS','Libra sudsudanesa','SSP'),
            (160,'España','Spain','ES','Euro','EUR'),
            (161,'Sri Lanka','Sri Lanka','LK','Rupia srilanquesa','LKR'),
            (162,'Estado de Libia','State of Libya','LY','Dinar','LYD'),
            (163,'Sudán','Sudan','SD','Libra sudanesa','SDG'),
            (164,'Surinam','Suriname','SR','Dólar surinamés','SRD'),
            (165,'Suecia','Sweden','SE','Corona','SEK'),
            (166,'Suiza','Switzerland','CH','Franco suizo','CHF'),
            (167,'República Árabe Siria','Syrian Arab Rep.','SY','Libra siria','SYP'),
            (168,'Tayikistán','Tajikistan','TJ','Somoni','TJS'),
            (169,'República Unida de Tanzania','Tanzania','TZ','Chelín tanzano','TZS'),
            (170,'Tailandia','Thailand','TH','Baht','THB'),
            (171,'Timor-Leste','Timor-Leste','TL','Dólar estadounidense','USD'),
            (172,'Togo','Togo','TG','Franco CFA','XOF'),
            (173,'Tonga','Tonga','TO','Pa anga','TOP'),
            (174,'Trinidad y Tobago','Trinidad and Tobago','TT','Dólar trinitense','TTD'),
            (175,'Túnez','Tunisia','TN','Dinar','TND'),
            (176,'Türkiye','Türkiye','TR','Lira turca','TRY'),
            (177,'Turkmenistán','Turkmenistan','TM','Manat','TMT'),
            (178,'Tuvalu','Tuvalu','TV','Dólar australiano','AUD'),
            (179,'Uganda','Uganda','UG','Chelín ugandés','UGX'),
            (180,'Ucrania','Ukraine','UA','Grivna','UAH'),
            (181,'Emiratos Árabes Unidos','United Arab Emirates','AE','Dirham','AED'),
            (182,'Reino Unido de Gran Bretaña e Irlanda del Norte','United Kingdom of Great Britain and Northern Ireland','GB','Libra esterlina','GBP'),
            (183,'Estados Unidos de América','United States of America','US','Dólar estadounidense','USD'),
            (184,'Uruguay','Uruguay','UY','Peso uruguayo','UYU'),
            (185,'Uzbekistán','Uzbekistan','UZ','Som','UZS'),
            (186,'Vanuatu','Vanuatu','VU','Vatu','VUV'),
            (187,'Ciudad del Vaticano','Vatican','VA','Euro','EUR'),
            (188,'Venezuela','Venezuela','VE','Bolívar soberano','VES'),
            (189,'Vietnam','Viet Nam','VN','Dong','VND'),
            (190,'Yemen','Yemen','YE','Rial yemení','YER'),
            (191,'Zambia','Zambia','ZM','Kwacha','ZMW'),
            (192,'Zimbabue','Zimbabwe','ZW','Dólar estadounidense','USD')
        ");
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('DROP SEQUENCE country_id_seq CASCADE');
        $this->addSql('DROP TABLE country');
    }
}
